
["The Blaze Burner Factors(temperature = 800 * factor, rate = 10 * factor)"]
	#Factor when the burner is extinguished
	extinguished_factor = 0.5
	#Factor when the burner is kindled
	kindled_factor = 1.0
	#Factor when the burner is seething
	seething_factor = 2.0

["The Polishing Percentages"]
	#The damage to item when polishing
	polishing_damage = 0.1
	#The shield provided when polishing
	polishing_shield = 0.1

["The Crushing"]
	#The damage to tool with crushing modifier
	crushing_damage = 5

["The Tinker's Machines"]
	#The ratio of the range to the normal fan
	fan_range = 1.5
	#The ratio of the speed to the normal drill
	drill_speed = 2.0
	#The damage to entity from the silk touch drill
	silk_touch_drill_damage = 1.0
	#The fortune level of the fortune drill
	fortune_drill_level = 3

