#List of screen names or packages to blacklist, example: ["com.modid.ScreenName", "com.modid.screens"]
screensBlacklist = []
#If true, prints opened screen name to identify it.
printScreenName = false

