# Don't change this! Version used to track needed updates.
version = 0
chickenFeathers = true
parrotFeathers = true
snowGolemSnowflakes = true
allayMagicDensity = 0.2
vexMagicDensity = 0.2
sheepShearFluff = true
improvedDragonFireballTrail = true
dragonsBreathClouds = true
commandBlockMinecartParticles = "ON"
endCrystalParticles = true
minecartSparksDisplayType = "LAND_ON_RAIL"
minecartSparksDensity = 0.5
slimeTrails = true
magmaCubeTrails = true
replaceSlimeSquishParticles = true
replaceOozingEffectParticles = true
replaceSpellCasterParticles = true
ironGolemCrackParticles = true
spectralArrowParticles = true
wardenDeathSoulParticles = true
freezingSnowFlakes = true
featherTicklingPandas = true
improvedPandaSneezes = true
villagerWorkAtWorkstationParticles = true
improvedBrownMooshroomFeedingEffects = true
improvedMooshroomShearingEffects = true
replaceBlazeSmoke = true
animalFeedingParticles = true
animalFeedingSoundVolume = 1.0

[sleeping]
playerSnoreChance = 0.0
playerSnoreSoundVolume = 0.0
playersHaveSleepingZs = true
villagerSnoreChance = 0.0
villagerSnoreSoundVolume = 0.0
villagersHaveSleepingZs = true
foxesHaveSleepingZs = true
batsHaveSleepingZs = true
catsHaveSleepingZs = true
otherMobsHaveSleepingZs = true
displaySleepingZsOnlyWhenSnoring = false
adjustNameTagWhenSleeping = true

[humanoids]
drowningBubblesDisplayType = "DEFAULT"
drowningBubblesDensity = 3
drowningBubbleAlpha = 1.0
forceDrowningBubblesToColumn = false
potionRingsDisplayType = "DEFAULT"
potionRingsParticleType = "BOTH"
NPCsHavePotionRings = true

[humanoids.frostyBreath]
displayType = "DEFAULT"
alpha = 0.5
waitTime = 60
seasons = "DEFAULT"
additionalBiomes = [  ]

[humanoids.player]
enableBreathingEffectsInCreative = true
stomachGrowlingThreshold = 0
stomachGrowlingVolume = 1.0
stomachGrowlingWaitTime = 15
heartBeatingThreshold = 0
heartbeatVolume = 1.0
heartBeatingWaitTime = 3

[dustClouds]
scale = 1.8455882
alpha = 1.0
preventWhenRaining = false
flyIntoWall = true
lessViewBlocking = false
playerFell = false
mobFell = false
landMaceAttack = true
playerRunning = false
mobRunning = false
playerRunningRequiresSpeed = false

[burning]
smoke = "DEFAULT"
flames = true
sparks = true
sounds = true
extinguishSteam = true

[explosives]
tntUpdateSmoke = true
tntFlamesDensity = 1
tntSparks = true
creeperSmoke = "UPDATED"
creeperSparks = true